image: registry.delite.ca/docker/docker:latest

variables:
  GIT_SUBMODULE_STRATEGY: recursive
  CONTAINER_BUILD_IMAGE: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME
  CONTAINER_RELEASE_IMAGE: $CI_REGISTRY_IMAGE:latest

stages:
  - build
  - release

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
  - app/node_modules/
  - app/index.js

before_script:
  - echo "//npm.delite.ca/:_authToken=\"${VERDACCIO_NPM_TOKEN_READONLY}\"" > ~/.npmrc
  - npm install --registry https://npm.delite.ca
  - git config --global user.email "gitlab-ci@delite.ca"
  - git config --global user.name "gitlab-ci"
  - git fetch --all --tags --prune
  - TAG=$(git describe --abbrev=0 --tags)

build:
  image: registry.delite.ca/docker/base/alpine/3_8:clojure-lein-node-jose
  stage: build
  only:
    - deploy
  tags:
    - linux
  script:
    - cd app
    - if ! git rev-parse --verify "$CI_COMMIT_REF_SLUG"; then git checkout tags/$TAG -b "$CI_COMMIT_REF_SLUG"; fi
    - npm version $TAG --no-git-tag-version --allow-same-version
    - lein cljsbuild once prod

release:
  stage: release
  tags:
    - linux
  only:
    - deploy
  script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker build -t $CONTAINER_RELEASE_IMAGE .
    - docker push $CONTAINER_RELEASE_IMAGE 

